# docker-compose.yml 
version: '3.8'

services:
    testci:
      build: jedis/testci:latest
      container_name: testci
      restart: unless-stopped
      ports:
        - 80:8080

volumes:
  octagon-db:
