# docker-compose.yml 
version: '3'

services:
    testci:
      image: jedis/testci:latest
      container_name: testci
      restart: unless-stopped
      ports:
        - 8080:8080

volumes:
  octagon-db:
